from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol, Sequence

from .models import (
    Action,
    AgentDecision,
    ContextBundle,
    Expectation,
    Finding,
    MemoryRecord,
    ModelResponse,
    Observation,
    PersonaRecord,
    ReplayResult,
    RunRecord,
    SessionRecord,
    ToolResult,
    VerificationResult,
)


class ModelClient(Protocol):
    async def decide(self, messages: Sequence[dict[str, Any]], decision_schema: dict[str, Any], generation_options: dict[str, Any]) -> ModelResponse: ...


class MemoryRepository(Protocol):
    async def append(self, record: MemoryRecord) -> MemoryRecord: ...
    async def search(self, run_id: str, persona_id: str | None, query: str, limit: int) -> list[MemoryRecord]: ...
    async def list_recent(self, run_id: str, persona_id: str | None, memory_type: str, limit: int) -> list[MemoryRecord]: ...
    async def get_by_ids(self, run_id: str, persona_id: str | None, ids: Sequence[str]) -> list[MemoryRecord]: ...
    async def supersede(self, run_id: str, persona_id: str | None, old_id: str, new_record: MemoryRecord) -> MemoryRecord: ...


class ContextAssembler(Protocol):
    async def build(self, persona: PersonaRecord, session: SessionRecord, observation: Observation, budgets: Any) -> ContextBundle: ...


class BrowserSession(Protocol):
    async def observe(self) -> Observation: ...
    async def execute(self, action: Action) -> ToolResult: ...
    async def save_state(self) -> Any: ...
    async def close(self) -> None: ...


class ToolRegistry(Protocol):
    def list_allowed(self, persona: PersonaRecord) -> list[dict[str, Any]]: ...
    async def dispatch(self, persona: PersonaRecord, action: Action) -> ToolResult: ...


class StateRepository(Protocol):
    async def create_run(self, run: RunRecord) -> RunRecord: ...
    async def get_run(self, run_id: str) -> RunRecord: ...
    async def transition_run(self, run_id: str, status: str) -> RunRecord: ...
    async def enqueue_session(self, session: SessionRecord) -> SessionRecord: ...
    async def lease_ready_session(self, owner: str, now: datetime, lease_seconds: int) -> SessionRecord | None: ...
    async def checkpoint_step(self, session_id: str, event: Any, next_session: SessionRecord) -> SessionRecord: ...
    async def append_event(self, event: Any) -> Any: ...
    async def list_events(self, run_id: str, after_sequence: int = -1, limit: int = 100) -> list[Any]: ...
    async def save_expectation(self, expectation: Expectation) -> Expectation: ...
    async def save_finding(self, finding: Finding) -> Finding: ...


class ScenarioController(Protocol):
    async def initialize(self, run: RunRecord) -> None: ...
    async def advance_phase(self, run: RunRecord) -> RunRecord: ...
    async def reset(self, run: RunRecord) -> None: ...
    def get_spec(self, scenario_id: str) -> dict[str, Any]: ...


class Verifier(Protocol):
    async def check(self, invariant_id: str, verification_context: Any) -> VerificationResult: ...


class ReplayService(Protocol):
    async def replay(self, finding_id: str) -> ReplayResult: ...
